"""initial schema

Revision ID: eac2cfd810ac
Revises: 
Create Date: 2026-10-01 12:35:42.409124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac2cfd810ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mapping_version', sa.String(length=32), nullable=False),
    sa.Column('chart_set_version', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed')", name=op.f('ck_analysis_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_table('chart_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('ante', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.CheckConstraint("model = 'chipev' OR model GLOB 'icm:?*'", name=op.f('ck_chart_sets_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_sets')),
    sa.UniqueConstraint('source', 'version', name=op.f('uq_chart_sets_source'))
    )
    op.create_table('hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('tournament_id', sa.String(length=64), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('ante', sa.Float(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('pokerstars', 'manual')", name=op.f('ck_hands_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hands')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_hands_source'))
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('hole_cards', sa.String(length=4), nullable=True),
    sa.Column('hand_class', sa.String(length=3), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('size_bb', sa.Float(), nullable=True),
    sa.Column('size_pot', sa.Float(), nullable=True),
    sa.Column('eff_stack_bb', sa.Float(), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=8), nullable=True),
    sa.Column('stage_source', sa.String(length=8), nullable=True),
    sa.Column('ev_loss', sa.Float(), nullable=True),
    sa.CheckConstraint("stage IN ('early', 'mid', 'bubble', 'itm', 'ft')", name=op.f('ck_decisions_stage')),
    sa.CheckConstraint("stage_source IN ('proxy', 'summary', 'manual')", name=op.f('ck_decisions_stage_source')),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_decisions_hand_id_hands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_hand_id'), ['hand_id'], unique=False)

    op.create_table('model_coefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tree_step', sa.String(length=32), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('se', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_model_coefs_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_coefs'))
    )
    with op.batch_alter_table('model_coefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_coefs_run_id'), ['run_id'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_set_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('stack_bucket', sa.String(length=32), nullable=False),
    sa.Column('sizing_bucket', sa.String(length=32), nullable=False),
    sa.Column('sizings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chart_set_id'], ['chart_sets.id'], name=op.f('fk_nodes_chart_set_id_chart_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    sa.UniqueConstraint('chart_set_id', 'key', 'stack_bucket', 'sizing_bucket', name=op.f('uq_nodes_chart_set_id'))
    )
    op.create_table('decision_node_map',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('mapping_version', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_node_map_decision_id_decisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_decision_node_map_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', 'mapping_version', name=op.f('pk_decision_node_map'))
    )
    with op.batch_alter_table('decision_node_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_node_map_node_id'), ['node_id'], unique=False)

    op.create_table('node_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=True),
    sa.Column('hand_group', sa.String(length=32), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('expected', sa.Float(), nullable=False),
    sa.Column('observed', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('bh_q', sa.Float(), nullable=True),
    sa.Column('unknown_stage_share', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_node_stats_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_node_stats_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_stats'))
    )
    with op.batch_alter_table('node_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_stats_run_id'), ['run_id'], unique=False)

    op.create_table('node_strategies',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('hand_class', sa.String(length=3), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('freq', sa.Float(), nullable=False),
    sa.CheckConstraint('freq >= 0 AND freq <= 1', name=op.f('ck_node_strategies_freq')),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_node_strategies_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'hand_class', 'action', name=op.f('pk_node_strategies'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_strategies')
    with op.batch_alter_table('node_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_stats_run_id'))

    op.drop_table('node_stats')
    with op.batch_alter_table('decision_node_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_node_map_node_id'))

    op.drop_table('decision_node_map')
    op.drop_table('nodes')
    with op.batch_alter_table('model_coefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_coefs_run_id'))

    op.drop_table('model_coefs')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_hand_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_actor'))

    op.drop_table('decisions')
    op.drop_table('hands')
    op.drop_table('chart_sets')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
